name: Staging Image Scans

on:
  workflow_dispatch: {}
  schedule:
  - cron: '30 11 * * *'

jobs:
  scan-container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers:
        - name: OWASP Juice Shop
          image: bkimminich/juice-shop
          appPort: 3000
        - name: DVNA 
          image: appsecco/dvna:sqlite
          appPort: 9090
        - name: BodgeIt Store
          image: owaspvwad/bodgeit
          appPort: 8080
    steps:
    - name: Get Runner IP Address
      id: runnerIp
      run: echo address=$(ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1) >> $GITHUB_OUTPUT
    - name: Start ${{ matrix.containers.name }} Container
      run: docker run --detach --publish 31337:${{ matrix.containers.appPort }} --name container ${{ matrix.containers.image }}
    - name: Scan Site
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: http://${{ steps.runnerIp.outputs.address }}:31337
    - name: Process Report
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: scan results (${{ matrix.containers.name }})
        report_paths: '**/dastardly-report.xml'
        require_tests: true
        detailed_summary: true