name: Staging Image Scans

on:
  workflow_dispatch: {}
  schedule:
  - cron: '30 11 * * *'

jobs:
  scan-container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers:
        - name: OWASP Juice Shop
          image: bkimminich/juice-shop
          appPort: 3000   
    steps:
    - name: Start ${{ matrix.containers.name }} Container
      run: docker run --detach --rm --publish 8080:${{ matrix.containers.appPort }} --name container ${{ matrix.containers.image }}
    - name: Scan Site
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: http://localhost:8080
    - name: Process Report
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: scan results (${{ matrix.sites }})
        report_paths: '**/dastardly-report.xml'
        require_tests: true
        detailed_summary: true