name: Website Scans

on:
  workflow_dispatch: {}
  schedule:
  - cron: '30 11 * * *'
  
env:
  sites: '["https://ginandjuice.shop/", "https://portswigger-labs.net/", "https://brokencrystals.com/"]'

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sites: ${{ fromJSON(env.sites) }}
    steps:
    - name: Dastardly Scan
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: ${{ matrix.sites }}
    - name: Process Report
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: scan results (${{ matrix.sites }})
        report_paths: '**/dastardly-report.xml'
        require_tests: true
        detailed_summary: true
  nuclei-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sites:
        - https://ginandjuice.shop/
        - https://portswigger-labs.net/
        - https://brokencrystals.com/
    steps:
    - name: Nuclei Scan
      uses: projectdiscovery/nuclei-action@main
      with:
        target: ${{ matrix.sites }}
        flags: "-severity critical,high,medium -stats"
  zap-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sites:
        - https://ginandjuice.shop/
        - https://portswigger-labs.net/
        - https://brokencrystals.com/
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: ${{ matrix.sites }}
        allow_issue_writing: false
