name: Website Scans

on:
  workflow_dispatch: {}
  schedule:
  - cron: '30 11 * * *'

jobs:
  target-list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: >-
          echo 'matrix=[
          "https://ginandjuice.shop/",
          "https://portswigger-labs.net/",
          "https://brokencrystals.com/",
          "https://www.reloadin5.com"
          ]' >> $GITHUB_OUTPUT
  dastardly-scan:
    needs: target-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sites: ${{ fromJson(needs.target-list.outputs.matrix) }}
    steps:
    - name: Dastardly Scan
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: ${{ matrix.sites }}
    - name: Process Report
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: scan results (${{ matrix.sites }})
        report_paths: '**/dastardly-report.xml'
        require_tests: true
        detailed_summary: true
  nuclei-scan:
    needs: target-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sites: ${{ fromJson(needs.target-list.outputs.matrix) }}
    steps:
    - name: Log File Name
      id: logfile
      run: echo name=$(echo ${{ matrix.sites }} | sed 's/\//_/g; s/:/_/g; s/\./_/g')_nuclei >> $GITHUB_OUTPUT
    - name: Nuclei Scan
      uses: projectdiscovery/nuclei-action@main
      with:
        target: ${{ matrix.sites }}
        flags: "-severity critical,high,medium -stats"
    - name: Upload nuclei log
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.logfile.outputs.name }}.log
        path: nuclei.log
  zap-scan:
    needs: target-list
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sites: ${{ fromJson(needs.target-list.outputs.matrix) }}
    steps:
    - name: Log File Name
      id: logfile
      run: echo name=$(echo ${{ matrix.sites }} | sed 's/\//_/g; s/:/_/g; s/\./_/g')_zap >> $GITHUB_OUTPUT
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: ${{ matrix.sites }}
        allow_issue_writing: false
        fail_action: true
    - name: Upload zap report
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.logfile.outputs.name }}.zip
        path: zap_scan.zip
